version: '3.4'

services:
  carservice:
    image: ${DOCKER_REGISTRY-}carservice
    ports: 
        - 7000:7000
        - 7010:7010
    build:
      context: .
      dockerfile: CarService/Dockerfile
    networks:
        - snet
    depends_on:
        - keycloak
    environment:
        - Oidc__Authority=http://keycloak:8080/auth/realms/demo
        - Oidc__ClientId=js-console

  postgres:
    image: postgres:latest
    ports:
        - 5432:5432
    volumes:
        - type: bind
          source: ./dbfile
          target: /var/lib/postgresql/data
    environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
    networks:
        - psqldb

  keycloak:
    image: jboss/keycloak:latest
    networks:
        - psqldb
        - snet
    environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: keycloak
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        JDBC_PARAMS: 'ssl=false&connectTimeout=30000'
    ports:
        - 9000:8080
    depends_on:
        - postgres

networks:
  psqldb:
    driver: bridge
  snet:
    driver: bridge
   